<?php

$menus = '[  
   {  
      "text":"CRM",
      "icon":"",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"DashBoard",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Leads",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Opportunity",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Enquiry",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Quote",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Sales Order",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Assy Review",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Cust Feedback",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Competitor",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Support",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":"",
            "children":[  
               {  
                  "text":"New SR",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               },
               {  
                  "text":"New RMA",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               },
               {  
                  "text":"New Eco",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               }
            ]
         },
         {  
            "text":"Solution",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"MES",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Planning",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Cap.Master",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Prod.Schdule",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Cap.Plan",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Cap.Chart",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"RCCP",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"CRP",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Purchasing",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"PO",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"RM Master",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Part Master",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Mtl Tracker",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Supp Master",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"WO",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Reg Wo",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Post Process",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Assy WO",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"BOM",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":""
   },
   {  
      "text":"Stores",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"GRN",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"NC",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"QA",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"NC",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Final Insp",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"FAIR",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Dispatch",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":""
   },
   {  
      "text":"Accounts",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Company",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Contacts",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Master Data",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":""
   },
   {  
      "text":"Production",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Operator",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Invoice",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Invoice",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Packing",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Pricing",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Excise",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Appendix",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"AR3A",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Utilities",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Email",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Calendar",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"FluentELM",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":"",
      "children":[  
         {  
            "text":"Summary",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Pre Boarding",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"OnBoarding",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Payroll",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Performance",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Exit Interview",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         },
         {  
            "text":"Project Mgmt",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":"",
            "children":[  
               {  
                  "text":"TMS",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               },
               {  
                  "text":"AMS",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               },
               {  
                  "text":"LMS",
                  "icon":"empty",
                  "href":"",
                  "target":"_self",
                  "title":""
               }
            ]
         },
         {  
            "text":"Resource Planning",
            "icon":"empty",
            "href":"",
            "target":"_self",
            "title":""
         }
      ]
   },
   {  
      "text":"Reports",
      "icon":"empty",
      "href":"",
      "target":"_self",
      "title":""
   }
]'


?>